# Generated by Django 5.2.13 on 2026-04-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('age', models.FloatField()),
                ('activity', models.FloatField()),
                ('length', models.FloatField()),
                ('gender', models.CharField(max_length=50)),
                ('ziel', models.CharField(max_length=50)),
            ],
        ),
    ]
