# Generated by Django 5.2.13 on 2026-04-12 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='currentdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(),
        ),
    ]
